"""Shared preprocessing and dataset I/O for the PlanetScope Gaza experiment.

This module deliberately contains no Sentinel code. Notebook 1 uses it to turn
the existing eight-band PlanetScope raster into one row-aligned NPZ/parquet
pair; later Planet notebooks import the same paths, channel names, split logic,
and compact model definitions instead of redefining the experiment contract.

Expected folder layout (``PLANET_DAMAGE_BASE`` points at this folder)::

    War-Damage-Detection/
        Data/own_footprints/
            Gaza_20240503_1_footprints.csv
            Gaza_20240706_1_footprints.csv
        Planet Data (Nils)/
            pipeline.py
            1_preprocessing_eda.ipynb
            rasters/
                gaza_20240503_ps_pre12m_forward1m_3m.tif
            datasets/
                Gaza_20240503_320a78e597.npz
                Gaza_20240503_320a78e597.parquet

In Colab, set ``PLANET_DAMAGE_BASE`` and (only if necessary)
``PLANET_LABEL_DIR`` before importing this module. Set ``PLANET_TEMP_DIR`` to
``/content/planet_damage_tmp`` to keep the multi-gigabyte temporary memory map
on Colab's fast local disk. On a checkout with the layout above, the persistent
paths default relative to this file.
"""

from __future__ import annotations

import hashlib
import json
import os
import random
import shutil
import zipfile
from pathlib import Path
from typing import Iterable, Sequence

import geopandas as gpd
import numpy as np
import pandas as pd
import rasterio
import torch
import torch.nn as nn
from numpy.lib.format import open_memmap
from rasterio.windows import Window
from sklearn.metrics import (
    average_precision_score,
    balanced_accuracy_score,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
)
from shapely.geometry import shape
from torch.utils.data import Dataset


# ---------------------------------------------------------------------------
# Paths and the on-disk preprocessing contract
# ---------------------------------------------------------------------------

MODULE_DIR = Path(__file__).resolve().parent
BASE_DIR = Path(os.environ.get("PLANET_DAMAGE_BASE", MODULE_DIR)).expanduser().resolve()
LABEL_DIR = Path(
    os.environ.get("PLANET_LABEL_DIR", BASE_DIR.parent / "Data" / "own_footprints")
).expanduser().resolve()
RASTER_DIR = Path(os.environ.get("PLANET_RASTER_DIR", BASE_DIR / "rasters")).expanduser().resolve()
DATASET_DIR = Path(os.environ.get("PLANET_DATASET_DIR", BASE_DIR / "datasets")).expanduser().resolve()
TEMP_DIR = Path(os.environ.get("PLANET_TEMP_DIR", DATASET_DIR)).expanduser().resolve()
EXPERIMENTS_DIR = Path(
    os.environ.get("PLANET_EXPERIMENTS_DIR", BASE_DIR / "experiments")
).expanduser().resolve()

CITY = "Gaza"
MAY_DATE = "20240503"
JULY_DATE = "20240706"
DATASET_ID = "320a78e597"  # fixed experiment identifier requested for this dataset
DATASET_STEM = f"{CITY}_{MAY_DATE}_{DATASET_ID}"

PLANET_RASTER_NAME = "gaza_20240503_ps_pre12m_forward1m_3m.tif"
PLANET_CHANNELS = (
    "ps_pre_B",
    "ps_pre_G",
    "ps_pre_R",
    "ps_pre_NIR",
    "ps_post_B",
    "ps_post_G",
    "ps_post_R",
    "ps_post_NIR",
)
RASTER_BAND_DESCRIPTIONS = (
    "pre_B",
    "pre_G",
    "pre_R",
    "pre_NIR",
    "post_B",
    "post_G",
    "post_R",
    "post_NIR",
)
PLANET_BANDS = ("B", "G", "R", "NIR")

PREP = {
    "sensor": "planet",
    "positive_damage_codes": (1, 2, 3),
    "label_geometry": "footprints",
    "label_date": MAY_DATE,
    "future_check_date": JULY_DATE,
    "future_damage_rule": "drop May class=0 when July class=1",
    "patch_size": 32,
    "scale_m": 3,
    "channels": PLANET_CHANNELS,
    "dtype": "float16",
    "n_sample": None,
    "seed": 0,
}


def ensure_directories() -> None:
    """Create only the two folder-local output/input-cache directories."""
    RASTER_DIR.mkdir(parents=True, exist_ok=True)
    DATASET_DIR.mkdir(parents=True, exist_ok=True)
    TEMP_DIR.mkdir(parents=True, exist_ok=True)
    EXPERIMENTS_DIR.mkdir(parents=True, exist_ok=True)


def label_path(date: str) -> Path:
    return LABEL_DIR / f"{CITY}_{date}_1_footprints.csv"


def planet_raster_path() -> Path:
    return RASTER_DIR / PLANET_RASTER_NAME


def dataset_paths() -> tuple[Path, Path]:
    return DATASET_DIR / f"{DATASET_STEM}.npz", DATASET_DIR / f"{DATASET_STEM}.parquet"


def preprocessing_fingerprint() -> str:
    """A content fingerprint stored inside the files, separate from DATASET_ID.

    ``DATASET_ID`` stays fixed because the requested filenames are an external
    contract.  This fingerprint makes configuration drift detectable without
    pretending that the supplied identifier was generated by this version of
    the code.
    """
    payload = {
        "city": CITY,
        "dataset_id": DATASET_ID,
        "raster": PLANET_RASTER_NAME,
        "prep": {
            **PREP,
            "positive_damage_codes": list(PREP["positive_damage_codes"]),
            "channels": list(PREP["channels"]),
        },
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


# ---------------------------------------------------------------------------
# Labels: May target plus a July-only false-negative guard
# ---------------------------------------------------------------------------

def _read_label_table(date: str) -> pd.DataFrame:
    path = label_path(date)
    if not path.exists():
        raise FileNotFoundError(f"Missing label file: {path}")

    raw = pd.read_csv(path, low_memory=False)
    required = {"system:index", "class", ".geo"}
    missing = required - set(raw.columns)
    if missing:
        raise ValueError(f"{path.name} is missing required columns: {sorted(missing)}")
    if raw["system:index"].isna().any() or raw["system:index"].duplicated().any():
        raise ValueError(f"{path.name} must contain unique, non-null system:index values")
    classes = set(raw["class"].dropna().astype(int).unique())
    if not classes <= {0, 1}:
        raise ValueError(f"{path.name} has non-binary class values: {sorted(classes)}")

    return raw


def build_filtered_buildings() -> tuple[gpd.GeoDataFrame, dict[str, int | float]]:
    """Build the canonical May table and remove labels contaminated by July.

    The May assessment supplies the target.  A building that is intact in May
    but damaged in July is excluded because the June Planet post composite may
    already show the later event.  May positives remain positives; May intact
    buildings are retained only when July also calls them intact.
    """
    # Keep July as a plain DataFrame. Parsing 218k duplicate polygons twice is
    # expensive in Colab and unnecessary because May is the geometry source.
    may_raw = _read_label_table(MAY_DATE)
    july_raw = _read_label_table(JULY_DATE)

    may_ids = set(may_raw["system:index"])
    july_ids = set(july_raw["system:index"])
    if may_ids != july_ids:
        raise ValueError(
            "May and July footprint IDs differ: "
            f"{len(may_ids - july_ids)} May-only and {len(july_ids - may_ids)} July-only"
        )

    may_raw_by_id = may_raw.set_index("system:index")
    july_raw_by_id = july_raw.set_index("system:index").loc[may_raw_by_id.index]
    geometry_mismatches = int((may_raw_by_id[".geo"] != july_raw_by_id[".geo"]).sum())
    if geometry_mismatches:
        raise ValueError(
            f"May and July contain {geometry_mismatches:,} footprint geometry mismatches"
        )

    may_by_id = may_raw_by_id
    july_by_id = july_raw_by_id
    y_may = may_by_id["class"].astype(np.int8)
    y_july = july_by_id["class"].astype(np.int8)

    # July is only a guard against contaminated May negatives. A May positive
    # remains a May positive even if the later release no longer contains that
    # assessment: cumulative UNOSAT releases can revise classifications or
    # omit earlier points, so treating 1 -> 0 as a true recovery would be wrong.
    may_positive_july_negative = (y_may == 1) & (y_july == 0)
    future_damage = (y_may == 0) & (y_july == 1)
    keep = ~future_damage

    kept_may = may_by_id.loc[keep]
    base_columns = [c for c in ("area",) if c in kept_may.columns]
    geometries = gpd.GeoSeries(
        [shape(json.loads(value)) for value in kept_may[".geo"]],
        index=kept_may.index,
        crs="EPSG:4326",
    )
    out = gpd.GeoDataFrame(
        kept_may[base_columns].copy(), geometry=geometries, crs="EPSG:4326"
    )
    out[f"class_{MAY_DATE}"] = y_may
    out[f"class_{JULY_DATE}"] = y_july
    out["class"] = y_may

    # Keep provenance and label-quality fields with explicit dates so later
    # modeling cannot accidentally confuse July information with a May input.
    for date, frame in ((MAY_DATE, may_by_id), (JULY_DATE, july_by_id)):
        for column in ("damage_pts", "severity", "confidence", "max_change"):
            if column in frame.columns:
                out[f"{column}_{date}"] = frame[column]

    out = out.reset_index()
    out = gpd.GeoDataFrame(out, geometry="geometry", crs="EPSG:4326")
    out = out.sort_values("system:index").reset_index(drop=True)

    geometry_ok = out.geometry.notna() & ~out.geometry.is_empty & out.geometry.is_valid
    invalid_geometry = int((~geometry_ok).sum())
    if invalid_geometry:
        out = out.loc[geometry_ok].reset_index(drop=True)

    summary: dict[str, int | float] = {
        "may_rows": int(len(may_by_id)),
        "future_damage_removed": int(future_damage.sum()),
        "may_positive_july_negative_kept": int(may_positive_july_negative.sum()),
        "invalid_geometry_removed": invalid_geometry,
        "filtered_rows": int(len(out)),
        "damaged": int(out["class"].sum()),
        "intact": int((out["class"] == 0).sum()),
        "damaged_fraction": float(out["class"].mean()),
    }
    return out, summary


def footprint_latitude_reference(date: str = MAY_DATE) -> pd.DataFrame:
    """Full notebook-0 footprint IDs and centroid latitudes for spatial bands.

    S1 fits latitude quantiles before applying imagery usability. Planet must
    therefore use this unfiltered reference rather than refitting cutoffs after
    future-damage and raster-coverage exclusions.
    """
    raw = _read_label_table(date)
    latitudes = np.fromiter(
        (shape(json.loads(value)).centroid.y for value in raw[".geo"]),
        dtype=np.float64,
        count=len(raw),
    )
    if not np.isfinite(latitudes).all():
        raise ValueError(f"{date} footprint centroids contain non-finite latitudes")
    return pd.DataFrame(
        {
            "system:index": raw["system:index"].astype(str).to_numpy(),
            "lat": latitudes,
        }
    )


# ---------------------------------------------------------------------------
# Raster checks and memory-aware extraction
# ---------------------------------------------------------------------------

def raster_metadata() -> dict[str, object]:
    path = planet_raster_path()
    if not path.exists():
        raise FileNotFoundError(f"Missing Planet raster: {path}")
    with rasterio.open(path) as src:
        return {
            "path": str(path),
            "bytes": path.stat().st_size,
            "driver": src.driver,
            "width": src.width,
            "height": src.height,
            "count": src.count,
            "crs": str(src.crs),
            "resolution": tuple(float(abs(v)) for v in src.res),
            "bounds": tuple(float(v) for v in src.bounds),
            "dtype": tuple(src.dtypes),
            "nodata": src.nodata,
            "descriptions": tuple(src.descriptions),
            "block_shapes": tuple(src.block_shapes),
        }


def validate_raster() -> dict[str, object]:
    meta = raster_metadata()
    if meta["count"] != len(PLANET_CHANNELS):
        raise ValueError(
            f"Planet raster has {meta['count']} bands; expected {len(PLANET_CHANNELS)}"
        )
    if not np.allclose(meta["resolution"], (PREP["scale_m"], PREP["scale_m"]), atol=1e-6):
        raise ValueError(
            f"Planet raster resolution is {meta['resolution']}; expected 3 m pixels"
        )
    descriptions = tuple(meta["descriptions"])
    if any(descriptions) and descriptions != RASTER_BAND_DESCRIPTIONS:
        raise ValueError(
            "Unexpected Planet band descriptions. "
            f"Found {descriptions}, expected {RASTER_BAND_DESCRIPTIONS}"
        )
    if meta["crs"] in (None, "None"):
        raise ValueError("Planet raster has no CRS")
    return meta


def _centres_and_windows(
    buildings: gpd.GeoDataFrame, src: rasterio.io.DatasetReader
) -> tuple[gpd.GeoDataFrame, np.ndarray, np.ndarray, np.ndarray]:
    patch = int(PREP["patch_size"])
    half = patch // 2

    projected = buildings.to_crs(src.crs).copy()
    centres = projected.geometry.centroid
    xs = centres.x.to_numpy(float)
    ys = centres.y.to_numpy(float)
    cols, rows = (~src.transform) * (xs, ys)
    r0 = np.round(rows).astype(np.int64) - half
    c0 = np.round(cols).astype(np.int64) - half
    fits = (
        (r0 >= 0)
        & (c0 >= 0)
        & (r0 + patch <= src.height)
        & (c0 + patch <= src.width)
    )

    centres_ll = gpd.GeoSeries(centres, crs=src.crs).to_crs("EPSG:4326")
    out = buildings.copy()
    out["lon"] = centres_ll.x.to_numpy(float)
    out["lat"] = centres_ll.y.to_numpy(float)
    out["centroid_x"] = xs
    out["centroid_y"] = ys
    out["raster_row"] = r0 + half
    out["raster_col"] = c0 + half
    return out, r0, c0, fits


def _temporary_paths(npz_path: Path, parquet_path: Path) -> tuple[Path, Path, Path]:
    tmp_x = TEMP_DIR / f".{DATASET_STEM}_X.tmp.npy"
    tmp_npz = DATASET_DIR / f".{npz_path.name}.part"
    tmp_parquet = DATASET_DIR / f".{parquet_path.name}.part"
    return tmp_x, tmp_npz, tmp_parquet


def _cleanup_temporary(paths: Iterable[Path]) -> None:
    for path in paths:
        try:
            path.unlink(missing_ok=True)
        except OSError:
            # Leave a diagnostic artifact rather than hiding the original error.
            pass


def extract_dataset(force: bool = False, progress_every: int = 10_000) -> dict[str, object]:
    """Extract and atomically save the Planet-only dataset.

    Raster tiles are read once with a half-patch halo and all building windows
    centred in that tile are extracted from the in-memory block. Pixels are
    written to a temporary float16 memory map, so the notebook never holds the
    full patch tensor in RAM. A patch is retained only when all eight bands are
    finite and unmasked for the complete 32 x 32 window.
    """
    ensure_directories()
    npz_path, parquet_path = dataset_paths()
    existing = (npz_path.exists(), parquet_path.exists())
    if all(existing) and not force:
        info = inspect_dataset(validate_alignment=True)
        print(f"Dataset already exists and passed validation: {npz_path.name}")
        return info
    if any(existing) and not all(existing) and not force:
        raise RuntimeError(
            "Only one member of the dataset pair exists. Inspect or remove the incomplete "
            f"pair before rerunning with force=True: {npz_path}, {parquet_path}"
        )

    buildings, label_summary = build_filtered_buildings()
    raster_info = validate_raster()
    tmp_x, tmp_npz, tmp_parquet = _temporary_paths(npz_path, parquet_path)
    _cleanup_temporary((tmp_x, tmp_npz, tmp_parquet))

    patch = int(PREP["patch_size"])
    n_channels = len(PLANET_CHANNELS)
    patches = None
    try:
        with rasterio.Env(GDAL_CACHEMAX=512):
            with rasterio.open(planet_raster_path()) as src:
                buildings, r0, c0, fits = _centres_and_windows(buildings, src)
                candidates = np.flatnonzero(fits)
                if not len(candidates):
                    raise RuntimeError("No filtered building has a complete patch inside the raster")

                block_h, block_w = src.block_shapes[0]
                half = patch // 2
                centre_rows = r0[candidates] + half
                centre_cols = c0[candidates] + half
                group_rows = centre_rows // block_h
                group_cols = centre_cols // block_w
                spatial_order = np.lexsort((group_cols, group_rows))
                candidates = candidates[spatial_order]
                group_rows = group_rows[spatial_order]
                group_cols = group_cols[spatial_order]

                patches = open_memmap(
                    tmp_x,
                    mode="w+",
                    dtype=np.float16,
                    shape=(len(candidates), n_channels, patch, patch),
                )
                kept_positions = np.empty(len(candidates), dtype=np.int64)
                n_valid = 0
                rejected_masked = 0
                rejected_nonfinite = 0

                # Read each 512-ish pixel raster tile once with a half-patch
                # halo, then take all building windows centred in that tile.
                # This turns ~200k small Drive reads into only a few hundred.
                boundaries = np.flatnonzero(
                    np.r_[True, (group_rows[1:] != group_rows[:-1]) |
                                   (group_cols[1:] != group_cols[:-1]), True]
                )
                examined = 0
                next_progress = progress_every if progress_every else None
                for start, stop in zip(boundaries[:-1], boundaries[1:]):
                    tile_row = int(group_rows[start])
                    tile_col = int(group_cols[start])
                    win_r0 = max(0, tile_row * block_h - half)
                    win_c0 = max(0, tile_col * block_w - half)
                    win_r1 = min(src.height, (tile_row + 1) * block_h + half)
                    win_c1 = min(src.width, (tile_col + 1) * block_w + half)
                    tile = src.read(
                        window=Window(win_c0, win_r0, win_c1 - win_c0, win_r1 - win_r0),
                        out_dtype="float32",
                        masked=True,
                    )

                    for position in candidates[start:stop]:
                        local_r0 = int(r0[position] - win_r0)
                        local_c0 = int(c0[position] - win_c0)
                        block = tile[
                            :,
                            local_r0:local_r0 + patch,
                            local_c0:local_c0 + patch,
                        ]
                        examined += 1
                        if block.shape != (n_channels, patch, patch):
                            raise RuntimeError(
                                f"Internal tiled-read error at building row {position}: "
                                f"got {block.shape}"
                            )
                        if np.ma.getmaskarray(block).any():
                            rejected_masked += 1
                        else:
                            values = np.asarray(block)
                            if not np.isfinite(values).all():
                                rejected_nonfinite += 1
                            else:
                                patches[n_valid] = values.astype(np.float16)
                                kept_positions[n_valid] = position
                                n_valid += 1

                        if next_progress is not None and examined >= next_progress:
                            print(
                                f"  examined {examined:,}/{len(candidates):,}; "
                                f"kept {n_valid:,}"
                            )
                            next_progress += progress_every

        if not n_valid:
            raise RuntimeError("Every geometrically eligible Planet patch was masked or non-finite")

        patches.flush()
        kept = buildings.iloc[kept_positions[:n_valid]].copy().reset_index(drop=True)
        kept["dataset_id"] = DATASET_ID
        kept["preprocessing_fingerprint"] = preprocessing_fingerprint()
        kept.to_parquet(tmp_parquet, index=False)

        y = kept["class"].to_numpy(np.int8)
        ids = kept["system:index"].astype(str).to_numpy(dtype=str)
        metadata = {
            "dataset_stem": DATASET_STEM,
            "preprocessing_fingerprint": preprocessing_fingerprint(),
            "prep": {
                **PREP,
                "positive_damage_codes": list(PREP["positive_damage_codes"]),
                "channels": list(PREP["channels"]),
            },
            "raster": raster_info,
            "software": {
                "numpy": np.__version__,
                "pandas": pd.__version__,
                "geopandas": gpd.__version__,
                "rasterio": rasterio.__version__,
            },
            "label_summary": label_summary,
            "geometric_candidates": int(len(candidates)),
            "outside_raster_removed": int(len(buildings) - len(candidates)),
            "masked_removed": int(rejected_masked),
            "nonfinite_removed": int(rejected_nonfinite),
            "saved_rows": int(n_valid),
        }
        # Passing an open file handle prevents numpy from appending another
        # .npz suffix to the atomic temporary filename.
        with tmp_npz.open("wb") as handle:
            np.savez_compressed(
                handle,
                X=patches[:n_valid],
                y=y,
                lat=kept["lat"].to_numpy(np.float64),
                channel_names=np.asarray(PLANET_CHANNELS),
                system_index=ids,
                metadata_json=np.asarray(json.dumps(metadata, sort_keys=True)),
            )

        # Existing complete files remain available until both replacements are
        # fully written.  Every file also carries IDs/fingerprint for alignment.
        os.replace(tmp_npz, npz_path)
        os.replace(tmp_parquet, parquet_path)
    finally:
        if patches is not None:
            try:
                patches.flush()
            except Exception:
                pass
            del patches
        _cleanup_temporary((tmp_x, tmp_npz, tmp_parquet))

    info = inspect_dataset(validate_alignment=True)
    print(
        f"Saved {info['rows']:,} Planet patches to {npz_path.name} "
        f"and {parquet_path.name}"
    )
    return info


# ---------------------------------------------------------------------------
# Lightweight inspection and downstream loading
# ---------------------------------------------------------------------------

def _npy_member_header(npz_path: Path, key: str) -> dict[str, object]:
    """Read an array's shape/dtype from an NPZ without decompressing its data."""
    member_name = f"{key}.npy"
    with zipfile.ZipFile(npz_path) as archive:
        if member_name not in archive.namelist():
            raise KeyError(f"{member_name} not found in {npz_path.name}")
        with archive.open(member_name) as member:
            version = np.lib.format.read_magic(member)
            if version == (1, 0):
                shape_, fortran, dtype_ = np.lib.format.read_array_header_1_0(member)
            elif version == (2, 0):
                shape_, fortran, dtype_ = np.lib.format.read_array_header_2_0(member)
            else:
                raise ValueError(
                    f"Unsupported NPY header version {version} for {member_name}"
                )
    return {"shape": tuple(shape_), "dtype": str(dtype_), "fortran_order": bool(fortran)}


def inspect_dataset(validate_alignment: bool = True) -> dict[str, object]:
    """Inspect the saved pair without inflating the multi-gigabyte X member."""
    npz_path, parquet_path = dataset_paths()
    if not npz_path.exists() or not parquet_path.exists():
        raise FileNotFoundError(f"Dataset pair not found: {npz_path}, {parquet_path}")

    x_header = _npy_member_header(npz_path, "X")
    with np.load(npz_path, allow_pickle=False) as data:
        y = data["y"].astype(np.int8)
        channel_names = tuple(str(v) for v in data["channel_names"].tolist())
        ids = data["system_index"].astype(str)
        metadata = json.loads(str(data["metadata_json"].item()))

    buildings = gpd.read_parquet(parquet_path)
    if validate_alignment:
        if x_header["shape"][0] != len(y) or len(y) != len(buildings):
            raise ValueError(
                f"Row mismatch: X={x_header['shape'][0]}, y={len(y)}, "
                f"parquet={len(buildings)}"
            )
        parquet_ids = buildings["system:index"].astype(str).to_numpy()
        if not np.array_equal(ids, parquet_ids):
            raise ValueError("NPZ system_index and parquet system:index are not row-aligned")
        parquet_fingerprints = set(
            buildings["preprocessing_fingerprint"].dropna().astype(str).unique()
        )
        if parquet_fingerprints != {metadata.get("preprocessing_fingerprint")}:
            raise ValueError(
                "NPZ and parquet preprocessing fingerprints do not describe the same export"
            )
        if set(buildings["dataset_id"].dropna().astype(str).unique()) != {DATASET_ID}:
            raise ValueError("Parquet dataset_id does not match the requested dataset")
        if channel_names != PLANET_CHANNELS:
            raise ValueError(f"Unexpected channels: {channel_names}")
        if tuple(x_header["shape"][1:]) != (
            len(PLANET_CHANNELS),
            PREP["patch_size"],
            PREP["patch_size"],
        ):
            raise ValueError(f"Unexpected X shape: {x_header['shape']}")
        if metadata.get("preprocessing_fingerprint") != preprocessing_fingerprint():
            raise ValueError("Saved preprocessing fingerprint does not match pipeline.py")

    return {
        "npz": str(npz_path),
        "parquet": str(parquet_path),
        "rows": int(len(y)),
        "damaged": int(y.sum()),
        "intact": int((y == 0).sum()),
        "damaged_fraction": float(y.mean()),
        "X_shape": x_header["shape"],
        "X_dtype": x_header["dtype"],
        "channels": channel_names,
        "npz_GB": npz_path.stat().st_size / 1e9,
        "parquet_MB": parquet_path.stat().st_size / 1e6,
        "metadata": metadata,
    }


def load_dataset(load_images: bool = True) -> dict[str, object]:
    """Load the saved pair for modeling.

    ``load_images=True`` inflates the compressed X member into RAM (roughly
    3.3 GB before raster-coverage filtering).  Notebook 1 should normally use
    :func:`inspect_dataset` and :func:`read_saved_patches` instead.
    """
    info = inspect_dataset(validate_alignment=True)
    npz_path, parquet_path = dataset_paths()
    with np.load(npz_path, allow_pickle=False) as data:
        result: dict[str, object] = {
            "y": data["y"].astype(np.int8),
            "lat": data["lat"].astype(np.float64),
            "channel_names": tuple(str(v) for v in data["channel_names"].tolist()),
            "system_index": data["system_index"].astype(str),
            "metadata": json.loads(str(data["metadata_json"].item())),
        }
        if load_images:
            result["X"] = data["X"]
    result["gdf"] = gpd.read_parquet(parquet_path)
    result["info"] = info
    return result


def read_saved_patches(
    rows: Sequence[int] | np.ndarray,
) -> tuple[np.ndarray, gpd.GeoDataFrame]:
    """Re-read selected saved rows from the raster for lightweight notebook EDA.

    This avoids decompressing the full NPZ.  Coordinates recorded in the
    parquet are the exact centres used during extraction.
    """
    _, parquet_path = dataset_paths()
    if not parquet_path.exists():
        raise FileNotFoundError(f"Missing dataset table: {parquet_path}")
    table = gpd.read_parquet(parquet_path)
    positions = np.asarray(rows, dtype=np.int64)
    if positions.ndim != 1 or (len(positions) and (positions.min() < 0 or positions.max() >= len(table))):
        raise IndexError("rows must be one-dimensional valid parquet row positions")

    patch = int(PREP["patch_size"])
    half = patch // 2
    out = np.empty((len(positions), len(PLANET_CHANNELS), patch, patch), np.float32)
    with rasterio.open(planet_raster_path()) as src:
        for k, position in enumerate(positions):
            row = int(table.iloc[position]["raster_row"])
            col = int(table.iloc[position]["raster_col"])
            block = src.read(
                window=Window(col - half, row - half, patch, patch), out_dtype="float32"
            )
            if block.shape != out[k].shape or not np.isfinite(block).all():
                raise RuntimeError(f"Saved row {position} no longer yields a valid Planet patch")
            out[k] = block
    return out, table.iloc[positions].copy()


# ---------------------------------------------------------------------------
# Notebook 2: spatial splitting, normalization, and Planet model definitions
# ---------------------------------------------------------------------------

def set_random_seed(seed: int, deterministic: bool = True) -> None:
    """Seed Python, NumPy and PyTorch for a reproducible experiment."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def latitude_quantile_spatial_split(
    table: pd.DataFrame,
    bands: dict[str, tuple[float, float]] | None = None,
    reference: pd.DataFrame | None = None,
) -> dict[str, object]:
    """Apply notebook 2's exact S1 latitude-quantile split to Planet rows.

    The defaults are train 0.55--1.00, stack 0.42--0.55, validation
    0.33--0.42, and test 0.00--0.33. There are no buffer gaps. ``reference``
    should be the full notebook-0 table from :func:`footprint_latitude_reference`.
    Bands are then joined to filtered Planet rows by footprint ID, matching S1's
    fit-bands-first, apply-imagery-usability-second order.
    """
    if bands is None:
        bands = {
            "train": (0.55, 1.00),
            "stack": (0.42, 0.55),
            "val": (0.33, 0.42),
            "test": (0.00, 0.33),
        }
    expected = ("train", "stack", "val", "test")
    if tuple(bands) != expected:
        raise ValueError(f"bands must be ordered exactly as {expected}")
    reference = table[["system:index", "lat"]].copy() if reference is None else reference.copy()
    required = {"system:index", "lat"}
    missing = required - set(reference.columns)
    if missing:
        raise ValueError(f"Latitude reference is missing columns: {sorted(missing)}")
    if reference["system:index"].isna().any() or reference["system:index"].duplicated().any():
        raise ValueError("Latitude reference IDs must be unique and non-null")
    reference["system:index"] = reference["system:index"].astype(str)
    latitude = reference["lat"].to_numpy(np.float64)
    if not np.isfinite(latitude).all():
        raise ValueError("Latitude contains non-finite values")

    masks: dict[str, np.ndarray] = {}
    thresholds: dict[str, tuple[float, float]] = {}
    for name, interval in bands.items():
        lo, hi = (float(value) for value in interval)
        if not 0 <= lo < hi <= 1:
            raise ValueError(f"Invalid quantile band for {name}: {interval}")
        qlo, qhi = np.quantile(latitude, [lo, hi])
        masks[name] = (latitude >= qlo) & (latitude <= qhi)
        thresholds[name] = (float(qlo), float(qhi))

    membership = np.stack([masks[name] for name in expected], axis=1).sum(axis=1)
    if (membership > 1).any():
        counts = {name: int(masks[name][membership > 1].sum()) for name in expected}
        raise ValueError(
            "Tied latitudes overlap S1 quantile boundaries; choose an explicit "
            f"tie rule before training. Overlap counts: {counts}"
        )
    if (membership == 0).any():
        raise ValueError("The S1 quantile bands do not assign every Planet row")

    reference_assignment = np.full(len(reference), "unused", dtype="U6")
    for name in expected:
        reference_assignment[masks[name]] = name
    role_by_id = pd.Series(
        reference_assignment, index=reference["system:index"], name="split_role"
    )
    table_ids = table["system:index"].astype(str)
    missing_ids = ~table_ids.isin(role_by_id.index)
    if missing_ids.any():
        raise ValueError(
            f"{int(missing_ids.sum()):,} Planet rows are absent from the split reference"
        )
    assignment = role_by_id.loc[table_ids].to_numpy(dtype="U6")
    indices: dict[str, np.ndarray] = {}
    for name in expected:
        indices[name] = np.flatnonzero(assignment == name)
        if not len(indices[name]):
            raise ValueError(f"Latitude split produced an empty {name} band")

    xy = table[["centroid_x", "centroid_y"]].to_numpy(np.float64)
    return {
        **indices,
        "assignment": assignment,
        "coordinate": latitude,
        "xy": xy,
        "bands": {name: tuple(map(float, bands[name])) for name in expected},
        "latitude_thresholds": thresholds,
        "reference_rows": int(len(reference)),
    }


def spatial_split_metadata(split: dict[str, object]) -> dict[str, object]:
    """JSON-serializable fitted split definition (indices stay out of JSON)."""
    return {
        "type": "s1_exact_latitude_quantile_bands",
        "bands": {name: list(values) for name, values in split["bands"].items()},
        "latitude_thresholds": {
            name: list(values) for name, values in split["latitude_thresholds"].items()
        },
        "buffer_m": 0.0,
        "reference_rows": split["reference_rows"],
        "counts": {
            name: int(len(split[name]))
            for name in ("train", "stack", "val", "test")
        },
    }


def planet_band_indices(bands: Sequence[str]) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """NPZ channel positions for matching pre/post Planet band names."""
    requested = tuple(str(band).upper() for band in bands)
    unknown = set(requested) - set(PLANET_BANDS)
    if unknown:
        raise ValueError(f"Unknown Planet bands: {sorted(unknown)}")
    if len(set(requested)) != len(requested):
        raise ValueError("Planet band list contains duplicates")
    pre = tuple(PLANET_CHANNELS.index(f"ps_pre_{band}") for band in requested)
    post = tuple(PLANET_CHANNELS.index(f"ps_post_{band}") for band in requested)
    return pre, post


def estimate_shared_percentiles(
    x: np.ndarray,
    train_indices: Sequence[int] | np.ndarray,
    bands: Sequence[str] = PLANET_BANDS,
    lower: float = 2.0,
    upper: float = 98.0,
    sample_patches: int = 20_000,
    seed: int = 0,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Estimate shared pre/post robust scaling from training rows only.

    One lower/upper pair is fitted per physical band using both acquisition
    periods. Sampling caps the percentile workspace while remaining fully
    reproducible. The returned third value contains the sampled row indices.
    """
    if not 0 <= lower < upper <= 100:
        raise ValueError("Percentiles must satisfy 0 <= lower < upper <= 100")
    indices = np.asarray(train_indices, dtype=np.int64)
    if not len(indices):
        raise ValueError("Cannot estimate normalization from an empty training split")
    if sample_patches and len(indices) > sample_patches:
        rng = np.random.default_rng(seed)
        sampled = np.sort(rng.choice(indices, size=sample_patches, replace=False))
    else:
        sampled = np.sort(indices)

    pre_indices, post_indices = planet_band_indices(bands)
    lo = np.empty(len(pre_indices), np.float32)
    hi = np.empty(len(pre_indices), np.float32)
    for j, (pre_i, post_i) in enumerate(zip(pre_indices, post_indices)):
        values = np.concatenate(
            [
                np.asarray(x[sampled, pre_i], dtype=np.float32).reshape(-1),
                np.asarray(x[sampled, post_i], dtype=np.float32).reshape(-1),
            ]
        )
        finite = values[np.isfinite(values)]
        if not len(finite):
            raise ValueError(f"Band {bands[j]} has no finite training pixels")
        lo[j], hi[j] = np.percentile(finite, [lower, upper]).astype(np.float32)
        if hi[j] <= lo[j]:
            raise ValueError(f"Band {bands[j]} has a degenerate normalization range")
        del values, finite
    return lo, hi, sampled


class PlanetPairDataset(Dataset):
    """Lazy normalized Planet pairs returned as one pre/post channel stack."""

    def __init__(
        self,
        x: np.ndarray,
        y: np.ndarray,
        indices: Sequence[int] | np.ndarray,
        bands: Sequence[str],
        lo: Sequence[float] | np.ndarray,
        hi: Sequence[float] | np.ndarray,
        augment: bool = False,
        brightness_jitter: float = 0.0,
    ) -> None:
        self.x = x
        self.y = np.asarray(y, dtype=np.float32)
        self.indices = np.asarray(indices, dtype=np.int64)
        self.pre_indices, self.post_indices = planet_band_indices(bands)
        self.lo = np.asarray(lo, dtype=np.float32)[:, None, None]
        self.scale = np.maximum(
            np.asarray(hi, dtype=np.float32)[:, None, None] - self.lo, 1e-6
        )
        self.augment = bool(augment)
        self.brightness_jitter = float(brightness_jitter)

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, item: int) -> tuple[torch.Tensor, torch.Tensor]:
        position = int(self.indices[item])
        patch = np.asarray(self.x[position], dtype=np.float32)
        pre = np.clip((patch[list(self.pre_indices)] - self.lo) / self.scale, 0, 1)
        post = np.clip((patch[list(self.post_indices)] - self.lo) / self.scale, 0, 1)
        x_t = torch.from_numpy(np.concatenate([pre, post], axis=0).copy())
        half = len(self.pre_indices)

        if self.augment:
            if torch.rand(()) < 0.5:
                x_t = torch.flip(x_t, dims=(2,))
            if torch.rand(()) < 0.5:
                x_t = torch.flip(x_t, dims=(1,))
            rotations = int(torch.randint(0, 4, ()).item())
            if rotations:
                x_t = torch.rot90(x_t, rotations, dims=(1, 2))
            if self.brightness_jitter:
                amount = self.brightness_jitter
                x_t[:half] = torch.clamp(
                    x_t[:half] + torch.empty(()).uniform_(-amount, amount), 0, 1
                )
                x_t[half:] = torch.clamp(
                    x_t[half:] + torch.empty(()).uniform_(-amount, amount), 0, 1
                )

        return x_t, torch.tensor(self.y[position], dtype=torch.float32)


def _planet_conv_block(cin: int, cout: int) -> nn.Sequential:
    """The exact convolutional block used by the S1 BaseCNN."""
    return nn.Sequential(
        nn.Conv2d(cin, cout, kernel_size=3, padding=1),
        nn.BatchNorm2d(cout),
        nn.ReLU(),
        nn.MaxPool2d(2),
    )


class BasePlanetCNN(nn.Module):
    """S1 BaseCNN unchanged except for the number of input channels."""

    def __init__(self, n_channels: int, width: int = 8, depth: int = 2, dropout: float = 0.2):
        super().__init__()
        chans = [n_channels] + [width * (2 ** i) for i in range(depth)]
        self.features = nn.Sequential(
            *[_planet_conv_block(chans[i], chans[i + 1]) for i in range(depth)]
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Dropout(dropout),
            nn.Linear(chans[-1], 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.head(self.features(x)).squeeze(1)


class SiamesePlanetCNN(nn.Module):
    """S1-style shared encoder with an explicit signed change feature."""

    def __init__(
        self,
        n_channels: int,
        width: int = 32,
        depth: int = 3,
        dropout: float = 0.4,
        head_dim: int = 128,
        head_dropout: float = 0.2,
    ):
        super().__init__()
        if n_channels % 2:
            raise ValueError("siamese_cnn needs matching pre and post channels")
        chans = [n_channels // 2] + [width * (2 ** i) for i in range(depth)]
        self.encoder = nn.Sequential(
            *[_planet_conv_block(chans[i], chans[i + 1]) for i in range(depth)],
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
        )
        self.half_channels = n_channels // 2
        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(3 * chans[-1], head_dim),
            nn.ReLU(),
            nn.Dropout(head_dropout),
            nn.Linear(head_dim, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        pre_features = self.encoder(x[:, : self.half_channels])
        post_features = self.encoder(x[:, self.half_channels :])
        joined = torch.cat(
            [pre_features, post_features, post_features - pre_features], dim=1
        )
        return self.head(joined).squeeze(1)


PLANET_MODEL_REGISTRY = {
    "base_cnn": BasePlanetCNN,
    "siamese_cnn": SiamesePlanetCNN,
}


def build_planet_model(
    name: str,
    n_channels: int,
    **model_parameters: object,
) -> nn.Module:
    if name not in PLANET_MODEL_REGISTRY:
        raise ValueError(f"Unknown Planet model {name}; choose {sorted(PLANET_MODEL_REGISTRY)}")
    return PLANET_MODEL_REGISTRY[name](n_channels=n_channels, **model_parameters)


@torch.inference_mode()
def predict_planet_probs(
    model: nn.Module,
    loader: torch.utils.data.DataLoader,
    device: torch.device | str,
) -> tuple[np.ndarray, np.ndarray]:
    """Return probabilities and labels in deterministic loader order."""
    model.eval()
    probabilities, labels = [], []
    for x, y in loader:
        logits = model(x.to(device, non_blocking=True))
        probabilities.append(torch.sigmoid(logits).cpu().numpy())
        labels.append(y.numpy())
    return np.concatenate(probabilities), np.concatenate(labels).astype(np.int8)


def neighbour_features(
    xy: np.ndarray,
    scores: np.ndarray,
    ks: Sequence[int] = (8, 32),
) -> pd.DataFrame:
    """Build leakage-safe spatial features within one split region only."""
    from sklearn.neighbors import BallTree

    xy = np.asarray(xy, dtype=np.float64)
    scores = np.asarray(scores, dtype=np.float32)
    if len(xy) != len(scores):
        raise ValueError("xy and scores must have the same number of rows")
    if any(int(k) < 1 for k in ks):
        raise ValueError("All neighbour counts must be positive")

    n = len(scores)
    features: dict[str, np.ndarray] = {"score": scores}
    if n < 2:
        for k in ks:
            for suffix in ("mean", "std", "max", "min", "dev", "dist"):
                features[f"k{k}_{suffix}"] = np.zeros(n, np.float32)
        return pd.DataFrame(features)

    tree = BallTree(xy)
    max_k = min(max(int(k) for k in ks) + 1, n)
    distances, neighbours = tree.query(xy, k=max_k)
    for k in ks:
        k_eff = min(int(k), max_k - 1)
        neighbour_scores = scores[neighbours[:, 1 : k_eff + 1]]
        neighbour_distances = distances[:, 1 : k_eff + 1]
        mean = neighbour_scores.mean(axis=1)
        features[f"k{k}_mean"] = mean
        features[f"k{k}_std"] = neighbour_scores.std(axis=1)
        features[f"k{k}_max"] = neighbour_scores.max(axis=1)
        features[f"k{k}_min"] = neighbour_scores.min(axis=1)
        features[f"k{k}_dev"] = scores - mean
        features[f"k{k}_dist"] = neighbour_distances.mean(axis=1)

    k_near = min(8, max_k - 1)
    nearest = np.sort(scores[neighbours[:, 1 : k_near + 1]], axis=1)[:, ::-1]
    for i in range(k_near):
        features[f"nb{i + 1}"] = nearest[:, i]
    return pd.DataFrame(
        {name: np.asarray(values, np.float32) for name, values in features.items()}
    )


def best_f1_threshold(y_true: np.ndarray, scores: np.ndarray) -> tuple[float, float]:
    precision, recall, thresholds = precision_recall_curve(y_true, scores)
    if not len(thresholds):
        return 0.5, 0.0
    f1 = 2 * precision[:-1] * recall[:-1] / np.maximum(
        precision[:-1] + recall[:-1], 1e-12
    )
    best = int(np.nanargmax(f1))
    return float(thresholds[best]), float(f1[best])


def binary_metrics(y_true: np.ndarray, scores: np.ndarray, threshold: float) -> dict[str, float | int]:
    y_true = np.asarray(y_true, dtype=np.int8)
    scores = np.asarray(scores, dtype=np.float64)
    predicted = (scores >= threshold).astype(np.int8)
    tn = int(((y_true == 0) & (predicted == 0)).sum())
    fp = int(((y_true == 0) & (predicted == 1)).sum())
    fn = int(((y_true == 1) & (predicted == 0)).sum())
    tp = int(((y_true == 1) & (predicted == 1)).sum())
    return {
        "n": int(len(y_true)),
        "prevalence": float(y_true.mean()),
        "threshold": float(threshold),
        "PR_AUC": float(average_precision_score(y_true, scores)),
        "ROC_AUC": float(roc_auc_score(y_true, scores)),
        "precision": float(precision_score(y_true, predicted, zero_division=0)),
        "recall": float(recall_score(y_true, predicted, zero_division=0)),
        "F1": float(f1_score(y_true, predicted, zero_division=0)),
        "balanced_accuracy": float(balanced_accuracy_score(y_true, predicted)),
        "specificity": float(tn / max(tn + fp, 1)),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp,
    }


def experiment_dirs(experiment_name: str) -> dict[str, Path]:
    """Create and return the persistent folders for one Planet experiment."""
    if not experiment_name or Path(experiment_name).name != experiment_name:
        raise ValueError("experiment_name must be one non-empty folder name")
    root = EXPERIMENTS_DIR / experiment_name
    dirs = {name: root / name for name in ("models", "metrics", "figures", "predictions")}
    dirs["root"] = root
    for path in dirs.values():
        path.mkdir(parents=True, exist_ok=True)
    return dirs


def atomic_json_dump(payload: object, path: str | Path) -> None:
    path = Path(path)
    tmp = path.with_name(f".{path.name}.part")
    with tmp.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
    os.replace(tmp, path)


def atomic_torch_save(payload: object, path: str | Path) -> None:
    path = Path(path)
    tmp = path.with_name(f".{path.name}.part")
    torch.save(payload, tmp)
    os.replace(tmp, path)


def preflight() -> pd.DataFrame:
    """One-row inventory suitable for notebook display before extraction."""
    ensure_directories()
    npz_path, parquet_path = dataset_paths()
    dataset_free = shutil.disk_usage(DATASET_DIR).free
    temp_free = shutil.disk_usage(TEMP_DIR).free
    rows = []
    for kind, path in (
        (f"labels {MAY_DATE}", label_path(MAY_DATE)),
        (f"labels {JULY_DATE}", label_path(JULY_DATE)),
        ("Planet raster", planet_raster_path()),
        ("dataset npz", npz_path),
        ("dataset parquet", parquet_path),
    ):
        rows.append(
            {
                "kind": kind,
                "exists": path.exists(),
                "size_GB": round(path.stat().st_size / 1e9, 3) if path.exists() else 0.0,
                "path": str(path),
                "dataset_dir_free_GB": round(dataset_free / 1e9, 1),
                "temp_dir_free_GB": round(temp_free / 1e9, 1),
            }
        )
    return pd.DataFrame(rows)


__all__ = [
    "BASE_DIR",
    "LABEL_DIR",
    "RASTER_DIR",
    "DATASET_DIR",
    "TEMP_DIR",
    "EXPERIMENTS_DIR",
    "CITY",
    "MAY_DATE",
    "JULY_DATE",
    "DATASET_ID",
    "DATASET_STEM",
    "PLANET_CHANNELS",
    "PLANET_BANDS",
    "RASTER_BAND_DESCRIPTIONS",
    "PREP",
    "label_path",
    "planet_raster_path",
    "dataset_paths",
    "preprocessing_fingerprint",
    "build_filtered_buildings",
    "footprint_latitude_reference",
    "raster_metadata",
    "validate_raster",
    "extract_dataset",
    "inspect_dataset",
    "load_dataset",
    "read_saved_patches",
    "set_random_seed",
    "latitude_quantile_spatial_split",
    "spatial_split_metadata",
    "planet_band_indices",
    "estimate_shared_percentiles",
    "PlanetPairDataset",
    "BasePlanetCNN",
    "SiamesePlanetCNN",
    "PLANET_MODEL_REGISTRY",
    "build_planet_model",
    "predict_planet_probs",
    "neighbour_features",
    "best_f1_threshold",
    "binary_metrics",
    "experiment_dirs",
    "atomic_json_dump",
    "atomic_torch_save",
    "preflight",
]
